apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-task-cluster10
  region: eu-west-1

nodeGroups:
  - name: nodegroup1
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 5
    availabilityZones: ["eu-west-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-eu-west-1a
      instance-type: onDemand
  - name: nodegroup2
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    availabilityZones: ["eu-west-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-eu-west-1b
      instance-type: onDemand
  - name: scale-spot
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    instancesDistribution:
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["eu-west-1a","eu-west-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateless-workload
      instance-type: spot

availabilityZones: ["eu-west-1a","eu-west-1b"]